const { response } = require('express');
const { validationResult } = require('express-validator');

const validarCampos = (req, res = response, next) => {
    /**
     *  obtain all the errors generated by the middlewares
     */
    const errores = validationResult(req);
    // check is there were errors
    if( !errores.isEmpty()){
        return res.status(400).json({
            ok: false,
            errors: errores.mapped()
        })
    }
    
    // si se llega a este punto no hubieron errores
    next();
}

module.exports = {
    validarCampos
}